# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestclick():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testclick(self):
    self.driver.get("https://ceshiren.com/")
    time.sleep(3)
    self.driver.set_window_size(922, 873)
    time.sleep(3)
    self.driver.find_element(By.LINK_TEXT, "所有分类").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#ember157 > a:nth-child(1)").click()
    time.sleep(3)
    element = self.driver.find_element(By.LINK_TEXT, "开源项目")
    time.sleep(3)
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.close()
  
